apiVersion: v1
kind: Pod
metadata:
  name: busybox
  annotations:
    qos.class: ls
  labels:
    label1: value1
    label2: value2
spec:
  containers:
  - name: c0-shared
    image: quay.io/crio/busybox:latest
    command:
      - sh
      - -c
      - sleep 3600
    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 100m
        memory: 100M
    imagePullPolicy: IfNotPresent
  - name: c1-shared
    image: quay.io/crio/busybox:latest
    command:
      - sh
      - -c
      - sleep 3600
    resources:
      requests:
        cpu: 250m
        memory: 100M
      limits:
        cpu: 250m
        memory: 100M
    imagePullPolicy: IfNotPresent
  - name: c2-exclusive
    image: quay.io/crio/busybox:latest
    command:
      - sh
      - -c
      - sleep 3600
    resources:
      requests:
        cpu: 1
        memory: 100M
      limits:
        cpu: 1
        memory: 100M
    imagePullPolicy: IfNotPresent
  - name: c3-exclusive
    image: quay.io/crio/busybox:latest
    command:
      - sh
      - -c
      - sleep 3600
    resources:
      requests:
        cpu: 1
        memory: 100M
      limits:
        cpu: 1
        memory: 100M
    imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 1
